server:
  port: 5918
spring:
  data:
    mongodb:
        uri: mongodb://icu:icu@127.0.0.1:27017/icu
  datasource:
    url: jdbc:mysql://localhost:3306/quertz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
#开启驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.nuc.zp: debug
